name: 'actions-zip-it'
description: 'A GitHub Action to create Git-friendly compressed archives, ensuring the hash remains consistent as long as the file content is identical.'
author: 'bluelovers'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  paths:
    description: 'List of file paths. Each file path must be on a newline.'
    required: true
  outputFile:
    description: 'outputFile path'
  autoCreateOutputDir:
    description: 'auto create outputFile path'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'
  hash:
    description: 'hash'

runs:
  using: node20
  main: dist/index.js
